name: "real_world/stl"
volume_complete: 1.0
time_limit: 1800

camera/horizontal_fov: 85.2
camera/vertical_fov: 58.0

raycast/dr:     0.1
raycast/dphi:   10
raycast/dtheta: 10

system/bbx/r: 0.3
system/bbx/overshoot: 0.25

aep/gain/r_min: 0
aep/gain/r_max: 7.0
aep/gain/zero: 2
aep/gain/lambda: 0.5
aep/gain/sigma_thresh: 0.2
aep/tree/extension_range: 0.5
aep/tree/max_sampling_radius: 7
aep/tree/initial_iterations: 200
aep/tree/cutoff_iterations: 400

rrt/min_nodes: 100
rrt/max_nodes: 1000

visualize_rays: false
visualize_tree: true
visualize_exploration_area: true

robot_frame: "fcu"
world_frame: "map"

# bounding box: necessary to limit the simulation 
# scenario (smaller than actual gazebo scenario)
boundary/min: [ -45, -45, 0.01 ] # [ -2.5, -1.0, 0.01 ] # [ -1.34, 0, 0.01 ] # [ -2.83,  -2.57, 0.2]
boundary/max: [ 45, 45, 1.25 ] # [ 4.5, 6.5, 1.5 ] # [ 3.45, 5.45, 1.5 ] # [ 2.28,   6.54,  1.5]

lambda: 0.5
min_distance: 0.8
max_distance: 2.0
min_distance_active: true
max_distance_active: true
routers_active: false
distance_add_path: 0.1
max_search_distance: 40.0
step_size: 0.1
